### ISSUE TITLE
support for category searching

### ISSUE THREAD

**Issue by trescube** [pelias/query#36]
libpostal can parse out categories from inputs, for example:

```
> restaurants lancaster, pa

Result:

{
  "category": "restaurants",
  "city": "lancaster",
  "state": "pa"
}
```

While FallbackQuery can search for a query term, it does not yet search for category terms.  Add support for this.

**Comment by dianashk** [comment]
I think this should be done as future work and doesn't need to be part of the initial release for libpostal integration.
