### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by vesameskanen** [pelias/query#42]
Happens in debian linux, node v.6.3.1, npm v3.10.0. Errors are:

 Failed Tests: There were 2 failures

```
address VariableStore with query AND street should only add query

  ✖ should be equivalent

address VariableStore with number+street and less granular fields should include all others

  ✖ should be equivalent
```

The outputted expected/actual strings for DeepEqual are identical, though.

**Comment by orangejulius** [comment]
Hey @vesameskanen,
We forgot to mention that we fixed this in https://github.com/pelias/query/pull/43, I'm sure you noticed :)
