### ISSUE TITLE
Support for ElasticSearch 5.6

### ISSUE THREAD

**Issue by arvindkartik** [pelias/query#95]
While pelias/schema repo is being upgraded to support ElasticSearch 5.6, after testing, I've found the following 

> #! Deprecation: Deprecated field [type] used, replaced by [match_phrase and match_phrase_prefix query]
> #! Deprecation: Deprecated field [slop] used, replaced by [match_phrase query]
> #! Deprecation: Deprecated field [optimize_bbox] used, replaced by [no replacement: `optimize_bbox` is no longer supported due to recent improvements]

Also over other examples I've noticed "minimum_number_should_match" is deprecated and replaced by "minimum_should_match".

Is there any plans to upgrade the query repo to support 5.6?

**Comment by missinglink** [comment]
Hi @arvindkartik, we noticed many `deprecation` warnings when testing `5.6`.

Fortunately those warnings are just warnings and are there to signal that this functionality is no longer available in 6+ but is still backwards compatible through 5.6.

We will address these issues when we [add support for Elasticsearch 6](https://github.com/pelias/pelias/issues/719)

If you have a good idea of the changes that need to be made we would welcome a pull request.
